server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
#            uri: file:///${user.home}\Desktop\delivery-configs-master\
             
#              uri: file:C:\Users\Lucas\Desktop\delivery-configs-master         
            
          uri: https://github.com/llucasdaniel/delivery-configs